workflows:
  ios-release:
    name: iOS Release Build
    integrations:
      app_store_connect:
        api_key: YusufStudio18  # Entegrasyon ismi (Codemagic panelinde oluşturduğun isim)
    environment:
      vars:
        XCODE_WORKSPACE: "YusufMail31.xcworkspace"
        XCODE_SCHEME: "YusufMail31"
        BUNDLE_ID: "com.yusufstudio18.yusufmail31"
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build iOS App
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $PWD/build/YusufMail31.xcarchive
    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true